# Generated by Django 4.2.7 on 2023-11-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=200)),
                ('slots', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
